### ISSUE TITLE
"Unsupported Table Versions"

### ISSUE THREAD

**Issue by peterb12** [csun/simple_gnucash_budget_plots#1]
I get this when I try to run this, with Gnucash 3.10.

```
(venv) simple_gnucash_budget_plots % python budget.py ~/Desktop/main.gnucash
Traceback (most recent call last):
  File "budget.py", line 246, in <module>
    main()
  File "budget.py", line 208, in main
    book = open_book(args.gnucash_file, open_if_lock=True)
  File "/Users/user/venv/lib/python3.7/site-packages/piecash/core/session.py", line 350, in open_book
    raise ValueError("Unsupported table versions")
ValueError: Unsupported table versions
(venv)simple_gnucash_budget_plots % file ~/Desktop/main.gnucash 
/Users/user/Desktop/main.gnucash: SQLite 3.x database, last written using SQLite version 3018000
```

**Comment by csun** [comment]
Thanks for finding this. I've just pushed a fix.

This is a bug in the `piecash` library where it doesn't support GnuCash 3.7+. They have a fix, but it's pretty recent so they haven't released a new build with it yet. I've added a flag `--unsupported_table_hotfix`. Please pass that when running the script and it should work. Please let me know if it doesn't.

**Comment by peterb12** [comment]
That worked great. Thanks!
