### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by peterb12** [csun/simple_gnucash_budget_plots#2]
I'm confused by the --budgets option, since in GnuCash as near as I can tell, budgets aren't identified by an integer.  What is it referring to?

**Comment by csun** [comment]
Another good contribution, thanks for the question. Seems I needed to do some more thorough explanation in the readme. Here's the section I've just added:


# Description
This script queries a SQLite GnuCash file for a given list of accounts, then plots them in a cumulative manner (so the plot line for Expenses will be its balance plus the sum of all of its child balances, Expenses:Food will be the sum of *its* balance plus child account balances, etc.)

In addition, this script plots a line on each report that shows a target "budget" value. Please note that the concept of a budget as used in this script is quite different from that used by GnuCash. In this script's case, each account has a single floating point budget, representing the target balance of that account each month.

This script will plot a year-to-date graph for each account for each year >= 2020, as well as separate graphs for each month of each plotted year, up to the current month. These can be dumped to a configurable `--output` directory, which defaults to the script directory.
